apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: llama-model
    serving.kserve.io/deploymentMode: RawDeployment
    argocd.argoproj.io/sync-wave: "1"
  name: llama-model
  namespace: rag
  finalizers:
    - inferenceservice.finalizers
    - odh.inferenceservice.finalizers
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  predictor:
    automountServiceAccountToken: false
    imagePullSecrets:
      - name: llama-model
    maxReplicas: 1
    minReplicas: 1
    model:
      args:
        - '--dtype=half'
        - '--max-model-len=20000'
        - '--gpu-memory-utilization=0.95'
        - '--enable-chunked-prefill'
        - '--enable-auto-tool-choice'
        - '--tool-call-parser=llama3_json'
        - '--chat-template=/opt/app-root/template/tool_chat_template_llama3.2_json.jinja'
      modelFormat:
        name: vLLM
      name: ''
      resources:
        limits:
          cpu: '2'
          memory: 14Gi
          nvidia.com/gpu: '1'
        requests:
          cpu: '1'
          memory: 10Gi
          nvidia.com/gpu: '1'
      runtime: llama-model
      storageUri: 'oci://quay.io/redhat-ai-services/modelcar-catalog:llama-3.2-3b-instruct'
    tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Equal
        value: 'true'