apiVersion: v1
kind: Secret
metadata:
  name: llama-stack-inference-model-secret
type: Opaque
stringData:
  INFERENCE_MODEL: "llama-model"
  VLLM_URL: "http://llama-model-predictor.rag.svc.cluster.local:8080/v1"
  VLLM_TLS_VERIFY: "false"
