apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  name: airplane-detection-wb
  namespace: airplane-detection
  labels:
    app: airplane-detection-wb
    opendatahub.io/dashboard: 'true'
    opendatahub.io/odh-managed: 'true'
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    notebooks.opendatahub.io/inject-oauth: 'true'
    opendatahub.io/image-display-name: CUDA
    opendatahub.io/accelerator-name: nvidia-gpu
    openshift.io/description: ''
    openshift.io/display-name: airplane-detection-wb
    notebooks.opendatahub.io/last-image-selection: 'minimal-gpu:2025.1'
    notebooks.opendatahub.io/last-size-selection: Medium
spec:
  template:
    spec:
      containers:
        - resources:
            limits:
              cpu: '6'
              memory: 24Gi
              nvidia.com/gpu: '1'
            requests:
              cpu: '3'
              memory: 24Gi
              nvidia.com/gpu: '1'
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /notebook/airplane-detection/airplane-detection-wb/api
              port: notebook-port
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          name: airplane-detection-wb
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /notebook/airplane-detection/airplane-detection-wb/api
              port: notebook-port
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          env:
            - name: NOTEBOOK_ARGS
              value: |-
                --ServerApp.port=8888
                --ServerApp.token=''
                --ServerApp.password=''
                --ServerApp.base_url=/notebook/airplane-detection/airplane-detection-wb
                --ServerApp.quit_button=False
                --ServerApp.tornado_settings={"user":"scientist1","hub_host":"REPLACE_BASE_URL","hub_prefix":"/projects/airplane-detection"}
            - name: JUPYTER_IMAGE
              value: 'image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/minimal-gpu:2025.1'
            - name: REQUESTS_CA_BUNDLE
              value: /etc/pki/tls/custom-certs/ca-bundle.crt
            - name: SSL_CERT_FILE
              value: /etc/pki/tls/custom-certs/ca-bundle.crt
            - name: PIPELINES_SSL_SA_CERTS
              value: /etc/pki/tls/custom-certs/ca-bundle.crt
            - name: GIT_SSL_CAINFO
              value: /etc/pki/tls/custom-certs/ca-bundle.crt
            - name: PIP_CERT
              value: /etc/pki/tls/custom-certs/ca-bundle.crt
          envFrom:
            - secretRef:
                name: model-storage-connection
          ports:
            - containerPort: 8888
              name: notebook-port
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /opt/app-root/src/
              name: airplane-detection-wb-storage
            - mountPath: /dev/shm
              name: shm
            - mountPath: /etc/pki/tls/custom-certs/ca-bundle.crt
              name: trusted-ca
              readOnly: true
              subPath: ca-bundle.crt
            - mountPath: /opt/app-root/pipeline-runtimes/
              name: runtime-images
          image: 'image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/minimal-gpu:2025.1'
          workingDir: /opt/app-root/src
        - resources:
            limits:
              cpu: 100m
              memory: 64Mi
            requests:
              cpu: 100m
              memory: 64Mi
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /oauth/healthz
              port: oauth-proxy
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          name: oauth-proxy
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /oauth/healthz
              port: oauth-proxy
              scheme: HTTPS
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - containerPort: 8443
              name: oauth-proxy
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /etc/oauth/client
              name: oauth-client
            - mountPath: /etc/oauth/config
              name: oauth-config
            - mountPath: /etc/tls/private
              name: tls-certificates
          image: 'registry.redhat.io/openshift4/ose-oauth-proxy@sha256:4f8d66597feeb32bb18699326029f9a71a5aca4a57679d636b876377c2e95695'
          args:
            - '--provider=openshift'
            - '--https-address=:8443'
            - '--http-address='
            - '--openshift-service-account=airplane-detection-wb'
            - '--cookie-secret-file=/etc/oauth/config/cookie_secret'
            - '--cookie-expire=24h0m0s'
            - '--tls-cert=/etc/tls/private/tls.crt'
            - '--tls-key=/etc/tls/private/tls.key'
            - '--upstream=http://localhost:8888'
            - '--upstream-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt'
            - '--email-domain=*'
            - '--skip-provider-button'
            - '--client-id=airplane-detection-wb-airplane-detection-oauth-client'
            - '--client-secret-file=/etc/oauth/client/secret'
            - '--scope=user:info user:check-access'
            - '--openshift-sar={"verb":"get","resource":"notebooks","resourceAPIGroup":"kubeflow.org","resourceName":"airplane-detection-wb","namespace":"$(NAMESPACE)"}'
            - '--logout-url=REPLACE_BASE_URL/projects/airplane-detection?notebookLogout=airplane-detection-wb'
      enableServiceLinks: false
      serviceAccountName: airplane-detection-wb
      tolerations:
        - effect: NoSchedule
          key: nvidia.com/gpu
          operator: Exists
      volumes:
        - name: airplane-detection-wb-storage
          persistentVolumeClaim:
            claimName: airplane-detection-wb-storage
        - emptyDir:
            medium: Memory
          name: shm
        - configMap:
            items:
              - key: ca-bundle.crt
                path: ca-bundle.crt
            name: workbench-trusted-ca-bundle
            optional: true
          name: trusted-ca
        - name: oauth-config
          secret:
            defaultMode: 420
            secretName: airplane-detection-wb-oauth-config
        - name: oauth-client
          secret:
            defaultMode: 420
            secretName: airplane-detection-wb-oauth-client
        - name: tls-certificates
          secret:
            defaultMode: 420
            secretName: airplane-detection-wb-tls
        - configMap:
            name: pipeline-runtime-images
            optional: true
          name: runtime-images
