resources:
  - ../base

configMapGenerator:
  - name: git-config
    namespace: openshift-gitops
    literals:
      - GIT_REPO_URL=https://github.com/cmays20/OpenShift-AI-Demo.git
      - GIT_REVISION=HEAD

replacements:
  - source:
      kind: ConfigMap
      name: git-config
      fieldPath: data.GIT_REPO_URL
    targets:
      - select:
          kind: Application
        fieldPaths:
          - spec.source.repoURL
  - source:
      kind: ConfigMap
      name: git-config
      fieldPath: data.GIT_REVISION
    targets:
      - select:
          kind: Application
        fieldPaths:
          - spec.source.targetRevision
    
