apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhoai
  namespace: redhat-ods-operator
spec:
  channel: stable
  installPlanApproval: Automatic
  name: rhods-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace