apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airplane-detection
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: gitops/Airplane-Detection/overlay
    repoURL: GITREPO
    targetRevision: REVISION
  syncPolicy:
    automated:
      selfHeal: true