apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: odf-lite
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: gitops/Operators/ODF/aggregate/aws-multiCloudGateway
    repoURL: 'GITREPO'
    targetRevision: REVISION
  syncPolicy:
    automated:
      selfHeal: true