apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-mesh
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: gitops/Operators/ServiceMesh/aggregate
    repoURL: 'GITREPO'
    targetRevision: REVISION
  syncPolicy:
    automated:
      selfHeal: true