apiVersion: v1
kind: Secret
metadata:
  name: htpass-secret
  namespace: openshift-config
type: Opaque
data:
  htpasswd: c2NpZW50aXN0MTokMnkkMDUkVFNrQ25QTVdUWHVja251OXZKSDlYdXFVTDRvQkxVWXl2Qi9TRXYxSE1ncmZDZklZSDdQQ2UKc2NpZW50aXN0MjokMnkkMDUkQTJ3ZXFoamVVaVl2a05DUmxZWUppZVVOTGRiTHFkVzR4Wkk0bTJQbGFMUnVEbm94QmJQTksKYWRtaW46JDJ5JDA1JEw4Rk1WWFk0dmh3azFWbFJYeXI1L09qR2NlZ2U4dXpEVjFYdjhlS1F3YzdlcGxDOC9wbXNHCg==
